sudo: false

language: node_js
node_js:
  - node # latest stable

env:
  - ELM_VERSION=0.18.0 ELM_TEST_VERSION=0.18.2 ELM_DOC_TEST_VERSION=2.2.3

cache:
  directories:
    - sysconfcpus
    - elm-stuff
    - tests/elm-stuff
    - benchmarks/elm-stuff

install:
  # Travis exposes a few more CPUs (like... 14 more) than the code can actually
  # use. This program allows us to lie to the compiler about how many CPUs it
  # can use. In this case, we're actually telling the truth about the number of
  # usable CPUs, so build times go way down.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

  - npm install -g elm@${ELM_VERSION} elm-test@${ELM_TEST_VERSION} elm-doc-test@${ELM_DOC_TEST_VERSION}
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm package install --yes


script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm make --yes
  - elm-doc-test
  - elm-test
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "aac98e3186c3"
  - COMMIT_AUTHOR_EMAIL: "mail@ilias.xyz"
